air_block:
  id: 1
  side: 63
  top: 63
  bottom: 63
  isSolid: false
  isTransparent: true
  isLightSource: false
  light_level: 0
grass_block:
  id: 2
  side: 8
  top: 16
  bottom: 0
  isSolid: true
  isTransparent: false
  colorTopByBiome: true
sand:
  id: 3
  side: 1
  top: 1
  bottom: 1
  isSolid: true
  isTransparent: false
dirt:
  id: 4
  side: 0
  top: 0
  bottom: 0
  isSolid: true
  isTransparent: false
stone:
  id: 5
  side: 2
  top: 2
  bottom: 2
  isSolid: true
  isTransparent: false
oak_log:
  id: 6
  side: 12
  top: 20
  bottom: 20
  isSolid: true 
  isTransparent: false
oak_leaves:
  id: 7
  side: 28
  top: 28
  bottom: 28
  isSolid: true
  isTransparent: true
  isBlendable: true
oak_planks:
  id: 8
  side: 5
  top: 5
  bottom: 5
  isSolid: true 
  isTransparent: false
water_still:
  id: 9
  side: 11
  top: 10
  bottom: 10
  isSolid: false
  isTransparent: true